### ISSUE TITLE
Waterkotte Web API

### ISSUE THREAD

**Issue by SORC3r3r** [chboland/pywaterkotte#7]
Hi Christian,

I was wondering where you got the web API spec?
Is there a public API specification available? 🤔 

Cheers,
Jonas

**Comment by chboland** [comment]
Hello
Please excuse the late reply. Unfortunately I am not aware of any official API. I found out what is implemented here by reverse-engineering the web interface. I also found a PDF on the Internet that describes some fields, but it is easier to search for the value you are looking for via the web interface.
Are you looking for a specific value, or are there problems with your heat pump? Maybe I can help

Greetings Christian
